if has('nvim')
    set undodir=~/.nvim/undo//
else
    call plug#begin()
    Plug 'vhda/verilog_systemverilog.vim'
    call plug#end()
    set undodir=~/.vim/undo//
endif

set undofile

set nu
set textwidth=200
set nobackup
set ai
set cin
set cul
set cuc
set autoindent
set autochdir
set autoread
set hls
set incsearch
set fileencodings=ucs-bom,utf-8,cp936,gb18030,big5,euc-jp,euc-kr,latin1
set visualbell
set suffixesadd+=.v
set suffixesadd+=.vh
set suffixesadd+=.vhd
set suffixesadd+=.c
set suffixesadd+=.h
set ff=dos
set history=200
syntax on


au! BufNewFile,BufRead *.xdc setf tcl
filetype plugin indent on

set expandtab
set tabstop=4
set shiftwidth=4

autocmd FileType python,verilog,javascript,html,css setlocal expandtab shiftwidth=4 tabstop=4
autocmd FileType make,automake setlocal noexpandtab
let g:verilog_disable_indent_lst = 'module,eos'

set tags=./tags;,tags

colorscheme desert
