set nu
set textwidth=200
set nobackup
set undodir=~/.vim/undo//
set undofile
set ai
set cin
set cul
set cuc
set smartindent
set autochdir
set autoread
set hls
set fileencodings=ucs-bom,utf-8,cp936,gb18030,big5,euc-jp,euc-kr,latin1
set visualbell
set suffixesadd+=.v
set suffixesadd+=.vh
set suffixesadd+=.vhd
set suffixesadd+=.c
set suffixesadd+=.h
set ff=dos
set history=200
syntax on

filetype plugin indent on
set expandtab
set tabstop=4
set shiftwidth=4
autocmd FileType python,verilog,javascript,html,css setlocal expandtab shiftwidth=4 tabstop=4
autocmd FileType make,automake setlocal noexpandtab

set tags=./tags;,tags

colorscheme desert
